# fly.toml file generated for integra on 2022-08-19T19:26:02-07:00

app = "integra"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"
  dockerfile = "./apps/api/Dockerfile"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "cd apps/api && yarn start"
  

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
