name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: "${{ matrix.os }}"
    env:
      TURBO_TOKEN: "${{ secrets.TURBO_TOKEN }}"
      TURBO_TEAM: "${{ secrets.TURBO_TEAM }}"
      TURBO_REMOTE_ONLY: true
      SKIP_BUILD_STATIC_GENERATION: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build

  deploy-server:
    name: Deploy server
    timeout-minutes: 15
    env:
      FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"
      TURBO_TOKEN: "${{ secrets.TURBO_TOKEN }}"
      TURBO_TEAM: "${{ secrets.TURBO_TEAM }}"
      TURBO_REMOTE_ONLY: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only

  deploy-client:
    name: Deploy client
    needs: deploy-server
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook on Cloudflare Pages
        uses: joelwmale/webhook-action@master
        with:
          url: "${{ secrets.CLOUDFLARE_WEBHOOK_URL }}"
